Update release_build.yml

diff --git a/.github/workflows/release_build.yml b/.github/workflows/release_build.yml
--- a/.github/workflows/release_build.yml
+++ b/.github/workflows/release_build.yml
@@ -40,6 +40,7 @@ jobs:
         run: chmod +x gradlew
 
       - name: Decode the Keystore from Base64
+        if: ${{ secrets.KEY_BASE64 }}
         run: echo "${{ secrets.KEY_BASE64 }}" | base64 --decode > signingKey.jks
 
       - name: Sign app APK
@@ -50,26 +51,30 @@ jobs:
           signingKeyBase64: ${{ secrets.KEY_BASE64 }}
           alias: ${{ secrets.KEY_ALIAS }}
           keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
-          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}  
-        env:
-          BUILD_TOOLS_VERSION: "34.0.0"
+          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
 
       - name: Rename APK
-        run: mv app/build/outputs/apk/release/app-release-signed.apk WriteOn.apk
+        run: |
+          if [ -f app/build/outputs/apk/release/app-release-signed.apk ]; then
+            mv app/build/outputs/apk/release/app-release-signed.apk WriteOn.apk;
+          else
+            echo "APK not found!";
+            exit 1;
+          fi
 
       - name: Upload the APK
-        uses: actions/upload-artifact@v4.3.5
+        uses: actions/upload-artifact@v4
         with:
-          name: Write On
+          name: WriteOn
           path: WriteOn.apk
 
       - name: Install GitHub CLI
-        run: sudo apt-get install gh
+        uses: actions/setup-gh@v2
 
       - name: Create GitHub Release
         run: |
           gh release create v1.2 WriteOn.apk \
             --title "v1.2" \
-            --notes "January Update~" \
+            --notes "January Update~"
         env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
